INSERT INTO Services (URI, userID, dateAdded)
 VALUES
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_ncl.owl#gsn_csm_contour_map_raster', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_gs.owl#ps2pdf', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_custom.owl#sPARQLResultsToJSONGraph', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_imagej.owl#surfacePlotter', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_custom.owl#jsonGraph_OperatorPaths', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_gmt.owl#grdimage', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_imagemagick.owl#fits2png', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_gmt.owl#surface', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_ncl.owl#gsn_csm_contour_map', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_gmt.owl#grd2xyz_esri', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_gmt.owl#nearneighbor', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_gs.owl#pdf2png', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_custom.owl#csv2tabular', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_custom.owl#jsonGraph_DataTransformations', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_custom.owl#jsonBars_Instances', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_ncl.owl#gsn_csm_xy2_time_series', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_gmt.owl#psxy', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_custom.owl#int2Short', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_gmt.owl#psxyz', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_imagemagick.owl#spherize', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_gmt.owl#grdcontour', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_custom.owl#XYZDataFieldFilter', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_custom.owl#float2ShortThr', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_gs.owl#ps2png', 0, NOW()),
('http://visko.cybershare.utep.edu:5080/visko-web/registry/module_gmt.owl#grd2xyz', 0, NOW());
